mass 9.1 -> 9.2 renaming

diff --git a/debian/postgresql-9.2.preinst b/debian/postgresql-9.2.preinst
--- a/debian/postgresql-9.2.preinst
+++ b/debian/postgresql-9.2.preinst
@@ -4,7 +4,7 @@ set -e
 #DEBHELPER#
 
 rm_conffile() {
-    PKGNAME="postgresql-9.1"
+    PKGNAME="postgresql-9.2"
     CONFFILE="$1"
 
     if [ -e "$CONFFILE" ]; then
@@ -23,15 +23,15 @@ rm_conffile() {
 
 # earlier releases used per-version init scripts, now replaced with common one 
 if [ "$1" = "upgrade" ] || [ "$1" = "install" ] && \
-	dpkg --compare-versions "$2" le-nl "9.1~beta3-2"; then
-    rm_conffile /etc/init.d/postgresql-9.1
+	dpkg --compare-versions "$2" le-nl "9.2~beta3-2"; then
+    rm_conffile /etc/init.d/postgresql-9.2
 fi
 
 # DB format changed between beta 1 and 2
 if [ "$1" = "upgrade" ] || [ "$1" = "install" ] && \
-	dpkg --compare-versions "$2" lt-nl "9.1~beta2"; then
-    if pg_lsclusters -h | grep -q '^9.1'; then
-	echo "ERROR: The database format changed between beta 1 and 2. Please dump your 9.1 clusters first and remove them, before attempting to upgrade the package." >&2
+	dpkg --compare-versions "$2" lt-nl "9.2~beta2"; then
+    if pg_lsclusters -h | grep -q '^9.2'; then
+	echo "ERROR: The database format changed between beta 1 and 2. Please dump your 9.2 clusters first and remove them, before attempting to upgrade the package." >&2
 	exit 1
     fi
 fi
